/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMyGamesRouteImport } from './routes/_app.my-games'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppFinderRouteImport } from './routes/_app.finder'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as ApiAccountDeleteRouteImport } from './routes/api.account.delete'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyGamesRoute = AppMyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFinderRoute = AppFinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AppDashboardRoute
  '/finder': typeof AppFinderRoute
  '/inbox': typeof AppInboxRoute
  '/my-games': typeof AppMyGamesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/u/$username': typeof UUsernameRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AppDashboardRoute
  '/finder': typeof AppFinderRoute
  '/inbox': typeof AppInboxRoute
  '/my-games': typeof AppMyGamesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/u/$username': typeof UUsernameRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finder': typeof AppFinderRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/my-games': typeof AppMyGamesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/u/$username': typeof UUsernameRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sso-callback'
    | '/dashboard'
    | '/finder'
    | '/inbox'
    | '/my-games'
    | '/notifications'
    | '/profile'
    | '/api/health'
    | '/api/users'
    | '/u/$username'
    | '/api/account/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sso-callback'
    | '/dashboard'
    | '/finder'
    | '/inbox'
    | '/my-games'
    | '/notifications'
    | '/profile'
    | '/api/health'
    | '/api/users'
    | '/u/$username'
    | '/api/account/delete'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sso-callback'
    | '/_app/dashboard'
    | '/_app/finder'
    | '/_app/inbox'
    | '/_app/my-games'
    | '/_app/notifications'
    | '/_app/profile'
    | '/api/health'
    | '/api/users'
    | '/u/$username'
    | '/api/account/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUsersRoute: typeof ApiUsersRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-games': {
      id: '/_app/my-games'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof AppMyGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finder': {
      id: '/_app/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof AppFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinderRoute: typeof AppFinderRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMyGamesRoute: typeof AppMyGamesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFinderRoute: AppFinderRoute,
  AppInboxRoute: AppInboxRoute,
  AppMyGamesRoute: AppMyGamesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUsersRoute: ApiUsersRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
